package me.luajk.notes.model;

public class TbNotes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.cover_pic
     *
     * @mbggenerated
     */
    private String coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.destination_id
     *
     * @mbggenerated
     */
    private String destinationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notes.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.id
     *
     * @return the value of tb_notes.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.id
     *
     * @param id the value for tb_notes.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.cover_pic
     *
     * @return the value of tb_notes.cover_pic
     *
     * @mbggenerated
     */
    public String getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.cover_pic
     *
     * @param coverPic the value for tb_notes.cover_pic
     *
     * @mbggenerated
     */
    public void setCoverPic(String coverPic) {
        this.coverPic = coverPic == null ? null : coverPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.title
     *
     * @return the value of tb_notes.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.title
     *
     * @param title the value for tb_notes.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.content
     *
     * @return the value of tb_notes.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.content
     *
     * @param content the value for tb_notes.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.date
     *
     * @return the value of tb_notes.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.date
     *
     * @param date the value for tb_notes.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.status
     *
     * @return the value of tb_notes.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.status
     *
     * @param status the value for tb_notes.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.destination_id
     *
     * @return the value of tb_notes.destination_id
     *
     * @mbggenerated
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.destination_id
     *
     * @param destinationId the value for tb_notes.destination_id
     *
     * @mbggenerated
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId == null ? null : destinationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notes.user_id
     *
     * @return the value of tb_notes.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notes.user_id
     *
     * @param userId the value for tb_notes.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}