package me.luajk.notes.dao;

import me.luajk.notes.model.TbNotes;
import me.luajk.notes.model.TbNotesExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbNotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int countByExample(TbNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int deleteByExample(TbNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int insert(TbNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int insertSelective(TbNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    List<TbNotes> selectByExample(TbNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    TbNotes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNotes record, @Param("example") TbNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNotes record, @Param("example") TbNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNotes record);
}